//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto_Integrador.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Projeto_Integrador.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] _10_acertos_seguidos___conquista {
            get {
                object obj = ResourceManager.GetObject("_10_acertos_seguidos___conquista", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] _3_dias_seguidos___conquista {
            get {
                object obj = ResourceManager.GetObject("_3_dias_seguidos___conquista", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] _30_dias_seguidos___conquista {
            get {
                object obj = ResourceManager.GetObject("_30_dias_seguidos___conquista", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] _365_dias_seguidos___conquista {
            get {
                object obj = ResourceManager.GetObject("_365_dias_seguidos___conquista", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] _7_dias_seguidos___conquista {
            get {
                object obj = ResourceManager.GetObject("_7_dias_seguidos___conquista", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] _90_dias_seguidos___conquista {
            get {
                object obj = ResourceManager.GetObject("_90_dias_seguidos___conquista", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] mestre_de_produtividade___conquista {
            get {
                object obj = ResourceManager.GetObject("mestre_de_produtividade___conquista", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] mestre_de_redes___conquista {
            get {
                object obj = ResourceManager.GetObject("mestre_de_redes___conquista", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] mestre_de_segurança___conquista {
            get {
                object obj = ResourceManager.GetObject("mestre_de_segurança___conquista", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] mestre_em_hardware {
            get {
                object obj = ResourceManager.GetObject("mestre_em_hardware", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] Mestre_programação___conquista {
            get {
                object obj = ResourceManager.GetObject("Mestre_programação___conquista", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] Mestre_sistemas___conquista {
            get {
                object obj = ResourceManager.GetObject("Mestre_sistemas___conquista", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap perfil {
            get {
                object obj = ResourceManager.GetObject("perfil", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap prefil_certo {
            get {
                object obj = ResourceManager.GetObject("prefil certo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap prefil_certo_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("prefil_certo-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] Primeiro_quiz___conquista {
            get {
                object obj = ResourceManager.GetObject("Primeiro_quiz___conquista", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
